name: Build macOS Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    # Use Apple Silicon runner (macOS 14 on ARM64)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (ARM64)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'arm64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Package with PyInstaller (ARM64)
        run: |
          pyinstaller --onefile --windowed --target-arch arm64 macro.py

      - name: List dist contents
        run: ls -R dist

      - name: Upload macOS .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/*.app
